meta:
  siteName: Open Ticket AI
  tagline: Intelligent automation for OTRS, Znuny, and Zammad. German Engineering.
  logoUrl: /images/open-ticket-ai-logo.png
nav:
  - label: Products
    url: products
  - label: Services
    url: services
  - label: Docs
    url: docs
  - label: Blog
    url: blog
footer:
  brandName: Open Ticket AI
  brandTagline: Intelligent automation for OTRS, Znuny, and Zammad. German Engineering.
  socialHeading: Connect
  sections:
    - title: Product
      links:
        - label: Features
          url: products
        - label: Integrations
          url: services
        - label: Security
          url: docs
    - title: Company
      links:
        - label: About Us
          url: '#'
        - label: Careers
          url: '#'
        - label: Legal
          url: '#'
  social:
    - platform: github
      url: https://github.com/openticketai
      ariaLabel: GitHub
    - platform: linkedin
      url: https://www.linkedin.com/company/open-ticket-ai
      ariaLabel: LinkedIn
  legal:
    - label: Privacy Policy
      url: '#'
    - label: Imprint
      url: '#'
  copyright: Open Ticket AI UG. All rights reserved.

popularResources:
  title: Popular Resources
  groups:
    - title: Automation Engine
      basePath: docs/open-ticket-automation
      items:
        - docId: /guides/quick_start
          icon: RocketLaunchIcon
        - docId: /developers/config_rendering
          icon: CommandLineIcon
        - docId: /developers/ticket_system_integration
          icon: PuzzlePieceIcon
        - docId: /developers/plugin_development
          icon: ArrowsRightLeftIcon
    - title: Tagging-Engine
      basePath: docs/ticket-tagging
      items:
        - docId: /taxonomy-design
          icon: Squares2x2Icon
        - docId: /hardware-sizing
          icon: CpuChipIcon
        - docId: /using-model
          icon: ArrowPathIcon
        - docId: /tag-mapping
          icon: ChartBarIcon
