meta:
  siteName: Open Ticket AI
  tagline: Intelligent automation for OTRS, Znuny, and Zammad. German Engineering.
  logoUrl: /images/open-ticket-ai-logo.png
nav:
  - label: Products
    url: products
  - label: Services
    url: services
  - label: Docs
    url: docs
  - label: Blog
    url: blog
footer:
  brandName: Open Ticket AI
  brandTagline: Intelligent automation for OTRS, Znuny, and Zammad. German Engineering.
  socialHeading: Connect
  sections:
    - title: Product
      links:
        - label: Features
          url: products
        - label: Integrations
          url: services
        - label: Security
          url: docs
    - title: Company
      links:
        - label: About
          url: '#'
        - label: Data Privacy
          url: '#'
        - label: Legal Notice
          url: '#'
        - label: Terms & Conditions
          url: '#'
  social:
    - platform: github
      url: https://github.com/openticketai
      ariaLabel: GitHub
    - platform: linkedin
      url: https://www.linkedin.com/company/open-ticket-ai
      ariaLabel: LinkedIn
  copyright: Open Ticket AI UG. All rights reserved.

popularResources:
  title: Popular Resources
  groups:
    - title: Automation Engine
      basePath: docs/open-ticket-automation
      items:
        - docId: /guides/quick_start
          icon: RocketLaunchIcon
        - docId: /developers/config_rendering
          icon: CommandLineIcon
        - docId: /developers/ticket_system_integration
          icon: PuzzlePieceIcon
        - docId: /developers/plugin_development
          icon: ArrowsRightLeftIcon
    - title: Tagging-Engine
      basePath: docs/ticket-tagging
      items:
        - docId: /taxonomy-design
          icon: Squares2x2Icon
        - docId: /hardware-sizing
          icon: CpuChipIcon
        - docId: /using-model
          icon: ArrowPathIcon
        - docId: /tag-mapping
          icon: ChartBarIcon

legalInfo:
  companyName: Open Ticket AI UG
  ceo: John Doe
  address:
    street: Example Street 123
    city: Berlin
    zip: 10115
    country: Germany
  legalForm: UG (haftungsbeschränkt)
  vatId: DE123456789
  registerInfo: Amtsgericht Berlin (Charlottenburg), HRB 123456 B
  email: info@open-ticket-ai.com
  phone: +49 30 12345678
team:
  - name: Jane Smith
    role: Lead Developer
    pictureUrl: /images/team/jane-smith.png
    email: jane.smith@open-ticket-ai.com
    phoneNumber: +49 30 12345679

