#file: noinspection YAMLSchemaValidation
meta:
  siteName: Open Ticket AI
  tagline: Private, on‑premise AI for ticket automation.
  logoUrl: /images/open-ticket-ai-logo.png
nav:
  - label: Products
    url: products
  - label: Services
    url: services
  - label: Docs
    url: docs
  - label: Blog
    url: blog
footer:
  brandName: Open Ticket AI
  brandTagline: Private, on‑premise AI for ticket automation.
  socialHeading: Connect
  sections:
    - title: Product
      links:
        - label: Features
          url: products
        - label: Integrations
          url: services
        - label: Security
          url: docs
    - title: Company
      links:
        - label: About
          url: 'company/about'
        - label: Data Privacy
          url: company/data-privacy
        - label: Legal Notice
          url: 'company/legal-notice'
        - label: Terms & Conditions
          url: 'company/terms'
  social:
    - platform: linkedin
      url: https://www.linkedin.com/company/open-ticket-ai
      ariaLabel: LinkedIn
      iconName: simple-icons:linkedin
    - platform: youtube
      url: https://www.youtube.com/@openticketai
      ariaLabel: YouTube
      iconName: simple-icons:youtube
    - platform: github
      url: https://github.com/Softoft-Orga
      ariaLabel: GitHub
      iconName: simple-icons:github
    - platform: huggingface
      url: https://huggingface.co/openticketai
      ariaLabel: Hugging Face
      iconName: simple-icons:huggingface
    - platform: x
      url: https://x.com/OpenTicketAI
      ariaLabel: X (Twitter)
      iconName: simple-icons:x
  legal:
    - label: Terms & Conditions
      url: terms
  copyright: Open Ticket AI UG. All rights reserved.

popularResources:
  title: Popular Resources
  groups:
    - title: Automation Engine
      basePath: docs/open-ticket-automation
      items:
        - docId: /guides/quick_start
          icon: heroicons:rocket-launch
        - docId: /developers/config_rendering
          icon: heroicons:command-line
        - docId: /developers/ticket_system_integration
          icon: heroicons:puzzle-piece
        - docId: /developers/plugin_development
          icon: heroicons:arrows-right-left
    - title: Tagging-Engine
      basePath: docs/ticket-tagging
      items:
        - docId: /taxonomy-design
          icon: heroicons:squares-2x2
        - docId: /hardware-sizing
          icon: heroicons:cpu-chip
        - docId: /using-model
          icon: heroicons:arrow-path
        - docId: /tag-mapping
          icon: heroicons:chart-bar

legalInfo:
  companyName: Open Ticket AI UG
  ceo: Constanze Krishnaratne
  address:
    street: Viktoriastraße 14
    city: Mannheim
    zip: '68159'
    country: Germany
  legalForm: UG (haftungsbeschränkt)
  vatId: ''
  registerInfo: Amtsgericht Mannheim, HRB
  email: info@openticketai.com
  phone: +49 621 12345678
team:
  - name: Constanze Krishnaratne
    role: CEO
    description: Leading Open Ticket AI's strategy and product direction with a focus on transparency, trust, and operational impact.
    pictureUrl: team_constanze_krishnaratne
    email: constanze.krishnaratne@openticketai.com
    phoneNumber: +49 621 12345678
    linkedInUrl: https://www.linkedin.com/in/constanze-krishnaratne
  - name: Tobias Bueck
    role: CTO
    description: Developing AI models for ticket automation and ensuring reliable on-premise deployments with measurable impact.
    pictureUrl: team_tobias_bueck
    email: tobias.bueck@openticketai.com
    phoneNumber: +49 621 12345679
    linkedInUrl: https://www.linkedin.com/in/tobias-bueck

dataPrivacy:
  introduction: |
    Open Ticket AI UG (hereinafter "we" or "us") is committed to protecting your personal data and respecting your privacy rights in accordance with the General Data Protection Regulation (GDPR) and other applicable data protection laws. This Data Privacy Policy explains how we collect, use, process, and protect your personal information when you use our services.
  controller:
    title: Data Controller
    content: |
      Open Ticket AI UG
      Viktoriastraße 14
      68159 Mannheim, Germany
      Email: info@openticketai.com
      Phone: +49 621 12345678
  dataProcessing:
    title: Data We Collect and Process
    categories:
      - title: Contact Information
        description: When you contact us or request information about our services, we collect your name, email address, phone number, and company information.
        legalBasis: Your consent (Art. 6(1)(a) GDPR) or our legitimate interest in responding to inquiries (Art. 6(1)(f) GDPR)
      - title: Website Usage Data
        description: We collect technical information such as IP address, browser type, device information, and pages visited through cookies and analytics tools.
        legalBasis: Your consent (Art. 6(1)(a) GDPR) for cookies, and our legitimate interest in improving our website (Art. 6(1)(f) GDPR)
      - title: Service Data
        description: When you use our services, we process data necessary for service delivery, including ticket system data, configuration settings, and usage metrics.
        legalBasis: Performance of contract (Art. 6(1)(b) GDPR)
      - title: Communication Data
        description: We store correspondence and communications with you, including email exchanges and support tickets.
        legalBasis: Our legitimate interest in maintaining customer relationships (Art. 6(1)(f) GDPR)
  yourRights:
    title: Your Rights Under GDPR
    rights:
      - title: Right to Access
        description: You have the right to request a copy of the personal data we hold about you.
      - title: Right to Rectification
        description: You can request that we correct any inaccurate or incomplete personal data.
      - title: Right to Erasure
        description: You have the right to request deletion of your personal data under certain circumstances.
      - title: Right to Restriction
        description: You can request that we restrict the processing of your personal data in certain situations.
      - title: Right to Data Portability
        description: You have the right to receive your personal data in a structured, commonly used format and transfer it to another controller.
      - title: Right to Object
        description: You can object to the processing of your personal data based on legitimate interests or for direct marketing purposes.
      - title: Right to Withdraw Consent
        description: Where processing is based on consent, you can withdraw your consent at any time.
      - title: Right to Lodge a Complaint
        description: You have the right to lodge a complaint with a supervisory authority if you believe your data protection rights have been violated.
  dataSecurity:
    title: Data Security
    content: |
      We implement appropriate technical and organizational security measures to protect your personal data against unauthorized access, alteration, disclosure, or destruction. These measures include encryption, access controls, regular security assessments, and staff training on data protection practices. We continuously review and update our security measures to ensure the ongoing protection of your data.
  thirdPartyServices:
    title: Third-Party Services
    services:
      - name: Google Analytics
        purpose: Website analytics and performance monitoring
        provider: Google LLC
        privacyPolicy: https://policies.google.com/privacy
      - name: GitHub
        purpose: Code repository and version control
        provider: GitHub, Inc.
        privacyPolicy: https://docs.github.com/en/site-policy/privacy-policies/github-privacy-statement
      - name: Netlify
        purpose: Website hosting and content delivery
        provider: Netlify, Inc.
        privacyPolicy: https://www.netlify.com/privacy/
      - name: Streak CRM
        purpose: Customer relationship management
        provider: Streak, Inc.
        privacyPolicy: https://www.streak.com/privacy
  contact:
    title: Contact for Data Privacy Inquiries
    content: |
      If you have any questions about this Data Privacy Policy or wish to exercise your rights, please contact us at:

      Email: info@openticketai.com
      Phone: +49 621 12345678
      Address: Open Ticket AI UG, Viktoriastraße 14, 68159 Mannheim, Germany
  lastUpdated: January 2026

ui:
  ctaLabel: Contact Sales
  cookieBanner:
    title: We value your privacy
    description: We use cookies and analytics to improve your experience and understand how you use our website. For more information, please read our
    privacyPolicyText: Privacy Policy
    acceptText: Accept
    declineText: Decline
  contactForm:
    title: Contact Sales
    submitButtonText: Submit
    messageLabel: Message
    emailLabel: Email
    subjectLabel: Subject
    emailPlaceholder: your@email.com
    messagePlaceholder: How can we help you?
