slug: main
meta:
  siteName: Open Ticket AI
  tagline: Intelligent automation for OTRS, Znuny, and Zammad. German Engineering.
  logoUrl: /public/open-ticket-logo.png
nav:
  - label: Products
    url: /products/
  - label: Services
    url: /services/
  - label: Pricing
    url: /pricing/
  - label: Docs
    url: /docs/
  - label: Blog
    url: /blog/
footer:
  brandName: Open Ticket AI
  brandTagline: Intelligent automation for OTRS, Znuny, and Zammad. German Engineering.
  socialHeading: Connect
  sections:
    - title: Product
      links:
        - label: Features
          url: /products
        - label: Integrations
          url: /services
        - label: Security
          url: /docs
    - title: Company
      links:
        - label: About Us
          url: "#"
        - label: Careers
          url: "#"
        - label: Legal
          url: "#"
  social:
    - platform: github
      url: https://github.com/openticketai
      ariaLabel: GitHub
    - platform: linkedin
      url: https://www.linkedin.com/company/open-ticket-ai
      ariaLabel: LinkedIn
  legal:
    - label: Privacy Policy
      url: "#"
    - label: Imprint
      url: "#"
  copyright: Open Ticket AI UG. All rights reserved.

popularResources:
  title: Popular Resources
  groups:
    - title: Automation Engine
      items:
        - docId: docs/en/getting-started
          icon: RocketLaunchIcon
        - docId: docs/en/api-reference
          icon: CommandLineIcon
        - docId: docs/en/connectors
          icon: PuzzlePieceIcon
        - docId: docs/en/webhooks
          icon: ArrowsRightLeftIcon
    - title: Tagging Engine
      items:
        - docId: docs/en/taxonomy-design
          icon: Squares2x2Icon
        - docId: docs/en/hardware-sizing
          icon: CpuChipIcon
        - docId: docs/en/model-training
          icon: ArrowPathIcon
        - docId: docs/en/benchmarking
          icon: ChartBarIcon

