name: CI/CD Issue
description: Propose changes to CI/CD workflows, build processes, deployments, or automation
title: "[CI/CD] "
labels: [ "ci-cd", "needs-triage" ]
body:
  - type: markdown
    attributes:
      value: |
        ## CI/CD Issue
        Propose changes to continuous integration, deployment, build processes, or automation workflows.
        
        **Use this template for:** GitHub Actions workflows, build scripts, deployment pipelines, automation changes, environment configuration, and testing infrastructure.

  - type: dropdown
    id: cicd-change-type
    attributes:
      label: Type of CI/CD Change
      description: What type of CI/CD change are you proposing?
      options:
        - GitHub Actions Workflow
        - Build Process/Scripts
        - Deployment Pipeline
        - Test Automation
        - Environment Configuration
        - Release Automation
        - Quality Assurance (QA) Workflow
        - Security Scanning
        - Dependency Management
        - Performance Testing
        - Other
    validations:
      required: true

  - type: textarea
    id: affected-files
    attributes:
      label: Affected Files/Workflows
      description: List the workflows, scripts, or configuration files that will be affected
      placeholder: |
        - .github/workflows/ci.yml
        - .github/workflows/release.yml
        - scripts/build.sh
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description of Change
      description: Describe the CI/CD change you're proposing
      placeholder: "Add automated security scanning to the CI workflow using CodeQL..."
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation and Context
      description: Why is this change needed? What problem does it solve?
      placeholder: "Currently, we don't have automated security scanning, which means vulnerabilities could be introduced..."
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context (Optional)
      description: Any other information such as risk level, impact assessment, testing plan, rollback plan, or config examples
      placeholder: |
        Risk Level: Medium
        
        Impact: May increase build time by 2-3 minutes
        
        Testing: Will test in a fork with sample PRs
        
        Rollback: Revert the commit and re-run workflows
        
        Config example:
        ```yaml
        name: Security Scan
        on:
          push:
            branches: [main, dev]
        ```
