name: Documentation Request
description: Request improvements, clarifications, or additions to documentation
title: "[Docs] "
labels: ["documentation", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## Documentation Request
        Help us improve the documentation for Open Ticket AI.

  - type: textarea
    id: current-state
    attributes:
      label: Current State
      description: What's currently documented (or missing)?
      placeholder: "The pipeline documentation mentions steps but doesn't explain..."
    validations:
      required: true

  - type: textarea
    id: proposed-improvement
    attributes:
      label: Proposed Improvement
      description: What should be added, changed, or clarified?
      placeholder: "Add a section explaining how depends_on works with examples..."
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context (Optional)
      description: Any other information such as use case, affected files, example content, or code snippets
      placeholder: |
        Affected file: docs/vitepress_docs/docs_src/en/developers/pipeline.md
        
        Example content:
        ```yaml
        - id: step_a
          use: "..."
        - id: step_b
          use: "..."
          depends_on: step_a
        ```
