name: Feature Request (General)
description: Suggest a new feature or enhancement for Open Ticket AI (not a specific pipe/plugin)
title: "[Feature] "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## Feature Request
        Suggest a new feature or enhancement for Open Ticket AI.
        
        **Note**: If you're requesting a new pipe or plugin, please use the "Pipe or Plugin Request" template instead.

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: Describe the feature you'd like to see
      placeholder: "Add support for hot-reloading configuration changes..."
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: How would you use this feature?
      placeholder: "In our production environment, we need to update configs without restarting..."
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution (Optional)
      description: How do you envision this working?
      placeholder: "Implement a file watcher that detects config changes and reloads..."

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context (Optional)
      description: Any other information such as alternatives considered, config examples, or references
      placeholder: "Similar to how Django handles this with autoreload..."