name: Pipe or Plugin Request
description: Request a new pipe, plugin, or extension to the pipeline system
title: "[Pipe/Plugin] "
labels: ["enhancement", "pipe-request", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## Pipe or Plugin Request
        Suggest a new pipe, plugin, or extension for Open Ticket AI's pipeline system.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What should this pipe/plugin do?
      placeholder: "A pipe that analyzes ticket content and assigns urgency level..."
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: How would you use this in your workflow?
      placeholder: |
        In our helpdesk, we need to automatically classify incoming tickets
        by urgency before routing them to the appropriate queue...
    validations:
      required: true

  - type: textarea
    id: config-example
    attributes:
      label: Configuration Example
      description: Show how this would be configured in YAML
      render: yaml
      placeholder: |
        - id: classify_urgency
          use: "open_ticket_ai.base:ClassifyUrgencyPipe"
          injects:
            model: ml_model
          config:
            urgency_levels:
              - low
              - medium
              - high
              - critical
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context (Optional)
      description: Any other information such as proposed name, input/output specs, dependencies, alternatives, or references
      placeholder: |
        Proposed name: ClassifyTicketByUrgencyPipe
        
        Input: PipeResult from previous step containing ticket data
        Output: PipeResult with urgency_level field added
        
        Dependencies: May require scikit-learn or similar ML library
        
        Similar to how system X handles this...
