# .github/ISSUE_TEMPLATE/unit_test_task.yml
name: "Unit Tests: <module>"
description: Minimal, behavior-focused pytest tests (no internals, no spam)
title: "tests: <module>"
labels: [ "tests", "unit" ]

body:
  - type: markdown
    attributes:
      value: |
        Goal: small, deterministic pytest tests for PUBLIC behavior only. Keep it minimal and maintainable.

  - type: input
    id: target
    attributes:
      label: Target module
      description: e.g. open_ticket_ai.core.foo
      placeholder: package.module

  - type: textarea
    id: behaviors
    attributes:
      label: Behaviors to cover
      description: Inputs → outputs, invariants, and exactly 1 negative/error case
      placeholder: |
        - normalize mixed case and whitespace
        - preserve underscores
        - raise ValueError on invalid input

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: Concrete pass/fail checks
      placeholder: |
        - Single test file for this target
        - ≤5 tests total, each ≤20 lines
        - Parametrized where applicable
        - No network/real FS; tmp_path for files
        - External effects isolated; deterministic results

  - type: checkboxes
    id: constraints
    attributes:
      label: Hard constraints
      options:
        - label: Public API only (no private attrs, no internals)
        - label: Use @pytest.mark.parametrize to compress cases
        - label: Prefer Fakes/DI over mocks for dependencies
        - label: Use pytest monkeypatch for env/globals; avoid unittest.mock unless unavoidable
        - label: If unittest.mock is used, set spec_set/autospec and avoid interaction over-assertion
        - label: Block external I/O (no network); use tmp_path/pyfakefs for files
        - label: Deterministic tests (fixed seeds/time; use freezegun/time-machine if needed)
        - label: ≤5 tests per file, ≤20 lines per test
        - label: Do not assert exact error messages; assert exception type (and stable code) only

  - type: textarea
    id: fixtures
    attributes:
      label: Shared setup / fixtures
      description: Reusable setup to place in tests/conftest.py (if any)

  - type: textarea
    id: parametrization
    attributes:
      label: Parametrized cases
      description: 3–6 representative examples


  - type: textarea
    id: artifacts
    attributes:
      label: Test artifacts (if any)
      description: Files under tmp_path and what to assert (existence, schema, flags)

  - type: checkboxes
    id: done
    attributes:
      label: Done when
      options:
        - label: Tests pass locally with `uv run pytest -q`
        - label: Ruff passes locally with `uv run ruff check . --fix`
        - label: Mypy passes locally with `uv run mypy .`
        - label: No implementation-coupled assertions
        - label: Duplicates consolidated via parametrization
        - label: Shared setup extracted to fixtures (if reused)
        - label: No forbidden I/O; external calls isolated
