slug: main
meta:
  siteName: Open Ticket AI
  tagline: Intelligente Automatisierung für OTRS, Znuny und Zammad. Deutsche Ingenieurskunst.
  logoUrl: /public/open-ticket-logo.png
nav:
  - label: Produkte
    url: products
  - label: Dienstleistungen
    url: services

  - label: Dokumentation
    url: docs
  - label: Blog
    url: blog
footer:
  brandName: Open Ticket AI
  brandTagline: Intelligent automation for OTRS, Znuny, and Zammad. German Engineering.
  socialHeading: Connect
  sections:
    - title: Produkt
      links:
        - label: Funktionen
          url: products
        - label: Integrationen
          url: services
        - label: Sicherheit
          url: docs
    - title: Unternehmen
      links:
        - label: Über uns
          url: '#'
        - label: Karriere
          url: '#'
        - label: Rechtliches
          url: '#'
  social:
    - platform: github
      url: https://github.com/openticketai
      ariaLabel: GitHub
    - platform: linkedin
      url: https://www.linkedin.com/company/open-ticket-ai
      ariaLabel: LinkedIn
  legal:
    - label: Datenschutz
      url: '#'
    - label: Impressum
      url: '#'
  copyright: Open Ticket AI UG. Alle Rechte vorbehalten.

popularResources:
  title: Beliebte Ressourcen
  groups:
    - title: Automatisierungs-Engine
      items:
        - docId: docs/guides/quick-start
          icon: RocketLaunchIcon
        - docId: docs/developers/config_rendering
          icon: CommandLineIcon
        - docId: docs/developers/ticket_system_integration
          icon: PuzzlePieceIcon
        - docId: docs/developers/plugin_development
          icon: ArrowsRightLeftIcon
    - title: Tagging-Engine
      items:
        - docId: docs/taxonomy-design
          icon: Squares2x2Icon
        - docId: docs/hardware-sizing
          icon: CpuChipIcon
        - docId: docs/using-model
          icon: ArrowPathIcon
        - docId: docs/tag-mapping
          icon: ChartBarIcon
