meta:
  siteName: Open Ticket AI
  tagline: Intelligente Automatisierung für OTRS, Znuny und Zammad. Deutsche Ingenieurskunst.
  logoUrl: /public/open-ticket-logo.png
nav:
  - label: Produkte
    url: products
  - label: Dienstleistungen
    url: services

  - label: Dokumentation
    url: docs
  - label: Blog
    url: blog
footer:
  brandName: Open Ticket AI
  brandTagline: Intelligent automation for OTRS, Znuny, and Zammad. German Engineering.
  socialHeading: Connect
  sections:
    - title: Produkt
      links:
        - label: Funktionen
          url: products
        - label: Integrationen
          url: services
        - label: Sicherheit
          url: docs
    - title: Unternehmen
      links:
        - label: Über uns
          url: '#'
        - label: Karriere
          url: '#'
        - label: Rechtliches
          url: '#'
  social:
    - platform: github
      url: https://github.com/openticketai
      ariaLabel: GitHub
    - platform: linkedin
      url: https://www.linkedin.com/company/open-ticket-ai
      ariaLabel: LinkedIn
  legal:
    - label: AGB
      url: terms
  copyright: Open Ticket AI UG. Alle Rechte vorbehalten.

popularResources:
  title: Beliebte Ressourcen
  groups:
    - title: Automatisierungs-Engine
      basePath: docs/open-ticket-automation
      items:
        - docId: /guides/quick_start
          icon: RocketLaunchIcon
        - docId: /developers/config_rendering
          icon: CommandLineIcon
        - docId: /developers/ticket_system_integration
          icon: PuzzlePieceIcon
        - docId: /developers/plugin_development
          icon: ArrowsRightLeftIcon
    - title: Tagging-Engine
      basePath: docs/ticket-tagging
      items:
        - docId: /taxonomy-design
          icon: Squares2x2Icon
        - docId: /hardware-sizing
          icon: CpuChipIcon
        - docId: /using-model
          icon: ArrowPathIcon
        - docId: /tag-mapping
          icon: ChartBarIcon

legalInfo:
  companyName: Open Ticket AI UG
  ceo: John Doe
  address:
    street: Beispielstraße 123
    city: Berlin
    zip: '10115'
    country: Deutschland
  legalForm: UG (haftungsbeschränkt)
  vatId: DE123456789
  registerInfo: Amtsgericht Berlin (Charlottenburg), HRB 123456 B
  email: info@open-ticket-ai.com
  phone: +49 30 12345678
team:
  - name: Jane Smith
    role: Lead Developer
    pictureUrl: /images/team/jane-smith.png
    email: jane.smith@open-ticket-ai.com
    phoneNumber: +49 30 12345679
