from __future__ import annotations

from pathlib import Path

import yaml

from docs.python_extras.scripts.doc_generation.generate_pipe_docs import generate_pipe_docs


def test_generate_pipe_docs_from_sidecar(tmp_path: Path) -> None:
    repo_root = Path(__file__).resolve().parents[4]
    sidecar_dir = repo_root / "docs" / "man_structured" / "pipes"
    source_root = repo_root / "src"

    output_root = tmp_path / "docs_src"
    generated = generate_pipe_docs(
        sidecar_dir=sidecar_dir,
        output_root=output_root,
        languages=("en",),
        source_root=source_root,
        section_dir=Path("pipes"),
        project_root=repo_root,
    )

    assert generated, "No documentation files were generated"
    output_file = generated[0]
    assert output_file.is_file()

    content = output_file.read_text(encoding="utf-8")
    assert "Add Note" in content
    assert "ticket_id" in content
    assert "Generated by python_extras.scripts.doc_generation.generate_pipe_docs" in content

    # Ensure frontmatter is valid YAML
    if content.startswith("---"):
        frontmatter_text = content.split("---", 2)[1]
        yaml.safe_load(frontmatter_text)
