items:
  - slug: open-ticket-ai-lite
    title: Open Ticket AI Lite
    tagline: Start automating your tickets with AI
    description: |
      Open Ticket AI Lite is the perfect entry point for small teams looking to
      automate their ticket classification and routing. Deploy on-premises with
      full control over your data.
    features:
      - Automatic ticket classification
      - Queue assignment
      - Priority detection
      - On-premises deployment
      - Community support
    tier: lite
    nav:
      group: Products
      order: 1
      hidden: false
    image: https://picsum.photos/1000/1000?blur=5

  - slug: open-ticket-ai-pro
    title: Open Ticket AI Pro
    tagline: Advanced AI for growing teams
    description: |
      Open Ticket AI Pro delivers enterprise-grade AI capabilities for medium to
      large support teams. Get advanced analytics, custom model training, and
      priority support.
    features:
      - Everything in Lite
      - Custom model training
      - Advanced analytics and reporting
      - Multi-language support
      - Priority email support
      - SLA guarantees
    tier: pro
    nav:
      group: Products
      order: 2
      hidden: false
    image: https://picsum.photos/800/400


  - slug: tagging-ai
    title: Tagging AI
    tagline: Automated classification with military-grade privacy
    description: |
      Automated classification with military-grade privacy. Deploy local LLMs to
      categorize tickets instantly without data leaving your perimeter.
    features:
      - Automated ticket classification
      - Local LLM deployment
      - Military-grade privacy
      - On-premises/Private cloud deployment
      - Multilingual support
      - No data leaves your perimeter
    tier: enterprise
    nav:
      group: Products
      order: 4
      hidden: false
    status: Coming Soon
    badges:
      - Coming Soon
      - On-Prem / Private Cloud
      - Multilingual
    image: https://picsum.photos/1000/1000?blur=5

  - slug: open-ticket-automation-core
    title: Open Ticket Automation Core
    tagline: The core engine for ticket automation
    description: |
      The renamed core engine. A secure API gateway that routes tickets between
      your helpdesk (Znuny/OTOBO) and our AI models. Built for high-throughput
      environments.
    features:
      - Secure API gateway
      - Routes tickets to AI models
      - Znuny/OTOBO integration
      - High-throughput performance
      - Enterprise-grade reliability
    tier: pro
    nav:
      group: Products
      order: 5
      hidden: false
    icon: heroicons:cube-transparent
    image: https://picsum.photos/800/400

