
import React from 'react';
import { Link } from 'react-router-dom';
import DocsLayout from '../components/DocsLayout';

const OtaDocs: React.FC = () => {
  const toc = [
    { label: "Introduction", id: "introduction" },
    { label: "Getting Started", id: "getting-started" },
    { label: "System Connectors", id: "connectors" },
    { label: "Automation Rules", id: "automation-rules" },
    { label: "API Reference", id: "api" }
  ];

  const breadcrumbs = [
    { label: "Documentation", to: "/docs" },
    { label: "Open Ticket Automation" }
  ];

  return (
    <DocsLayout toc={toc} breadcrumbs={breadcrumbs}>
      <section id="introduction" className="mb-20">
        <div className="inline-flex items-center gap-2 rounded-lg bg-purple-500/10 border border-purple-500/20 px-3 py-1 text-[10px] font-black uppercase text-purple-400 mb-6">
          <span className="material-symbols-outlined text-xs">auto_fix</span>
          Resolution Layer
        </div>
        <h1 className="text-4xl md:text-5xl font-black text-white mb-6 font-display">Open Ticket Automation (OTA)</h1>
        <p className="text-xl text-slate-400 leading-relaxed mb-8">
          OTA is the bridge between AI classification and helpdesk execution. It allows you to transform the tags generated by <Link to="/docs/tagging-ai" className="text-primary hover:underline">Tagging AI</Link> into concrete actions within OTRS, Znuny, and Zammad.
        </p>
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div className="p-6 rounded-xl bg-[#1a101f] border border-white/5">
            <span className="material-symbols-outlined text-primary mb-3">conversion_path</span>
            <h3 className="text-white font-bold mb-2">Actionable Routing</h3>
            <p className="text-xs text-slate-500 leading-relaxed">Automatically move tickets to the correct team queue based on AI intent detection.</p>
          </div>
          <div className="p-6 rounded-xl bg-[#1a101f] border border-white/5">
            <span className="material-symbols-outlined text-primary mb-3">priority_high</span>
            <h3 className="text-white font-bold mb-2">Dynamic Priority</h3>
            <p className="text-xs text-slate-500 leading-relaxed">Update SLAs and Priority fields instantly if AI detects critical sentiment or high impact.</p>
          </div>
        </div>
      </section>

      <section id="getting-started" className="mb-20 pt-16 border-t border-white/5">
        <h2 className="text-3xl font-bold text-white mb-6 font-display">Getting Started</h2>
        <p className="text-slate-400 mb-8 leading-relaxed">
          New to OTA? Follow our detailed step-by-step guide to deploy your first automation pipeline in under 15 minutes.
        </p>
        <Link to="/docs/ota/getting-started" className="inline-flex items-center gap-3 px-6 py-3 rounded-xl bg-white text-black font-black uppercase tracking-widest text-xs hover:scale-[1.02] transition-transform">
          Start the Tutorial
          <span className="material-symbols-outlined">arrow_forward</span>
        </Link>
      </section>

      <section id="connectors" className="mb-20 pt-16 border-t border-white/5">
        <h2 className="text-3xl font-bold text-white mb-6 font-display">System Connectors</h2>
        <p className="text-slate-400 mb-8 leading-relaxed">
          Connect to your existing infrastructure using our pre-built adapters.
        </p>
        <div className="space-y-4">
          {['OTOBO / Znuny (OTRS)', 'Zammad', 'Generic Webhook'].map((sys, i) => (
            <div key={i} className="group flex items-center justify-between p-5 rounded-xl bg-surface-dark border border-white/5 hover:border-primary/30 transition-all cursor-pointer">
              <div className="flex items-center gap-4">
                <div className="size-10 rounded-lg bg-white/5 flex items-center justify-center text-slate-500 group-hover:text-primary transition-colors">
                  <span className="material-symbols-outlined">cable</span>
                </div>
                <span className="text-white font-bold text-sm">{sys}</span>
              </div>
              <span className="material-symbols-outlined text-slate-600 group-hover:translate-x-1 transition-transform">chevron_right</span>
            </div>
          ))}
        </div>
      </section>

      <section id="automation-rules" className="mb-20 pt-16 border-t border-white/5">
        <h2 className="text-3xl font-bold text-white mb-6 font-display">Automation Rules</h2>
        <p className="text-slate-400 mb-8 leading-relaxed text-sm">
          Define your business logic in YAML. OTA evaluates these rules sequentially.
        </p>
        <div className="bg-[#150c19] rounded-xl p-6 border border-white/5 shadow-2xl">
           <pre className="text-xs text-slate-300 font-mono leading-relaxed overflow-x-auto cyber-scrollbar">
{`rules:
  - name: "Route Access Issues"
    condition: "tags.intent == 'access_request'"
    actions:
      - set_queue: "IT-Support::Access"
      - add_note: "AI routed this to Access Team"
      
  - name: "Escalate Critical"
    condition: "tags.urgency == 'critical'"
    actions:
      - set_priority: "5 extreme"
      - notify_slack: "#incidents-critical"`}
           </pre>
        </div>
      </section>

      <section id="api" className="mb-32 pt-16 border-t border-white/5">
        <h2 className="text-3xl font-bold text-white mb-6 font-display">API Reference</h2>
        <p className="text-slate-400 mb-6 leading-relaxed">
          Trigger OTA manually or from other systems using the REST API.
        </p>
        <div className="bg-surface-dark rounded-xl border border-white/5 overflow-hidden">
          <div className="bg-[#1a101f] px-6 py-3 border-b border-white/5 flex items-center justify-between">
            <span className="text-[10px] font-black uppercase text-green-400">POST</span>
            <span className="text-xs text-slate-400 font-mono">/v1/automation/process</span>
          </div>
          <div className="p-6">
            <p className="text-[10px] font-black text-slate-600 mb-4 uppercase tracking-widest">Payload Example:</p>
            <pre className="text-[11px] text-slate-300 bg-black/40 p-4 rounded-lg font-mono cyber-scrollbar">
{`{
  "ticket_id": "100234",
  "tags": {
    "intent": "billing_dispute",
    "urgency": "medium"
  }
}`}
            </pre>
          </div>
        </div>
      </section>
    </DocsLayout>
  );
};

export default OtaDocs;
