
import React from 'react';
import { Link } from 'react-router-dom';

const OtaDocs: React.FC = () => {
  return (
    <div className="min-h-screen bg-background-dark">
      {/* Sub-Header / Breadcrumbs */}
      <div className="border-b border-white/5 bg-[#0f0814]/50 sticky top-16 z-40 backdrop-blur-sm">
        <div className="max-w-7xl mx-auto px-6 h-12 flex items-center text-xs gap-2">
          <Link to="/docs" className="text-slate-500 hover:text-white transition-colors">Documentation</Link>
          <span className="material-symbols-outlined text-sm text-slate-700">chevron_right</span>
          <span className="text-primary font-bold">Open Ticket Automation</span>
        </div>
      </div>

      <div className="max-w-7xl mx-auto px-6 py-16 lg:flex gap-16">
        {/* Table of Contents - Sidebar */}
        <aside className="hidden lg:block w-64 flex-shrink-0 sticky top-32 h-fit">
          <h4 className="text-[10px] font-black uppercase tracking-widest text-slate-500 mb-6">On this page</h4>
          <nav className="flex flex-col gap-4 text-sm">
            <a href="#introduction" className="text-white font-bold border-l-2 border-primary pl-4">Introduction</a>
            <a href="#getting-started" className="text-slate-400 hover:text-white transition-colors pl-4 border-l-2 border-transparent hover:border-white/10">Getting Started</a>
            <a href="#connectors" className="text-slate-400 hover:text-white transition-colors pl-4 border-l-2 border-transparent hover:border-white/10">System Connectors</a>
            <a href="#automation-rules" className="text-slate-400 hover:text-white transition-colors pl-4 border-l-2 border-transparent hover:border-white/10">Automation Rules</a>
            <a href="#api" className="text-slate-400 hover:text-white transition-colors pl-4 border-l-2 border-transparent hover:border-white/10">API Reference</a>
          </nav>

          <div className="mt-12 p-6 rounded-2xl bg-primary/5 border border-primary/10">
            <h5 className="text-xs font-bold text-primary mb-2">Need Support?</h5>
            <p className="text-[11px] text-slate-400 mb-4">Our engineering team can assist with complex migrations.</p>
            <Link to="/services" className="text-[11px] font-bold text-white flex items-center gap-1 group">
              View Service Packs
              <span className="material-symbols-outlined text-xs group-hover:translate-x-1 transition-transform">arrow_forward</span>
            </Link>
          </div>
        </aside>

        {/* Main Content */}
        <div className="flex-1 max-w-3xl">
          <section id="introduction" className="mb-20">
            <div className="inline-flex items-center gap-2 rounded-lg bg-purple-500/10 border border-purple-500/20 px-3 py-1 text-[10px] font-black uppercase text-purple-400 mb-6">
              <span className="material-symbols-outlined text-xs">auto_fix</span>
              Resolution Layer
            </div>
            <h1 className="text-4xl md:text-5xl font-black text-white mb-6 font-display">Open Ticket Automation (OTA)</h1>
            <p className="text-xl text-slate-400 leading-relaxed mb-8">
              OTA is the bridge between AI classification and helpdesk execution. It allows you to transform the tags generated by <Link to="/docs" className="text-primary hover:underline">Tagging AI</Link> into concrete actions within OTRS, Znuny, and Zammad.
            </p>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div className="p-6 rounded-xl bg-[#1a101f] border border-white/5">
                <span className="material-symbols-outlined text-primary mb-3">conversion_path</span>
                <h3 className="text-white font-bold mb-2">Actionable Routing</h3>
                <p className="text-xs text-slate-500 leading-relaxed">Automatically move tickets to the correct team queue based on AI intent detection.</p>
              </div>
              <div className="p-6 rounded-xl bg-[#1a101f] border border-white/5">
                <span className="material-symbols-outlined text-primary mb-3">priority_high</span>
                <h3 className="text-white font-bold mb-2">Dynamic Priority</h3>
                <p className="text-xs text-slate-500 leading-relaxed">Update SLAs and Priority fields instantly if AI detects critical sentiment or high impact.</p>
              </div>
            </div>
          </section>

          <section id="getting-started" className="mb-20 pt-16 border-t border-white/5">
            <h2 className="text-3xl font-bold text-white mb-6 font-display">Getting Started</h2>
            <p className="text-slate-400 mb-6 leading-relaxed">
              OTA runs as a lightweight service alongside your ticket system or as a Docker container in your private cloud.
            </p>
            <div className="bg-black rounded-xl p-6 font-mono text-sm border border-slate-800 text-slate-300">
              <div className="flex justify-between items-center mb-4 text-[10px] text-slate-500 border-b border-slate-800 pb-2 uppercase tracking-widest">
                <span>Installation via Shell</span>
                <span>v2.4.0</span>
              </div>
              <p className="text-primary"># Pull the latest image</p>
              <p className="mb-2">docker pull ghcr.io/open-ticket-ai/ota:latest</p>
              <p className="text-primary"># Run with your config</p>
              <p>docker run -d -v /path/to/config.yaml:/app/config.yaml ota:latest</p>
            </div>
          </section>

          <section id="connectors" className="mb-20 pt-16 border-t border-white/5">
            <h2 className="text-3xl font-bold text-white mb-6 font-display">System Connectors</h2>
            <p className="text-slate-400 mb-8 leading-relaxed">
              Connect to your existing infrastructure using our pre-built adapters. Each adapter handles the specific API quirks of the target platform.
            </p>
            <div className="space-y-4">
              {['OTOBO / Znuny (OTRS)', 'Zammad', 'Generic Webhook'].map((sys, i) => (
                <div key={i} className="group flex items-center justify-between p-5 rounded-xl bg-surface-dark border border-white/5 hover:border-primary/30 transition-all cursor-pointer">
                  <div className="flex items-center gap-4">
                    <div className="size-10 rounded-lg bg-white/5 flex items-center justify-center text-slate-500 group-hover:text-primary transition-colors">
                      <span className="material-symbols-outlined">cable</span>
                    </div>
                    <span className="text-white font-bold">{sys}</span>
                  </div>
                  <span className="material-symbols-outlined text-slate-600 group-hover:translate-x-1 transition-transform">chevron_right</span>
                </div>
              ))}
            </div>
          </section>

          <section id="automation-rules" className="mb-20 pt-16 border-t border-white/5">
            <h2 className="text-3xl font-bold text-white mb-6 font-display">Automation Rules</h2>
            <p className="text-slate-400 mb-8 leading-relaxed">
              Define your business logic in YAML. OTA evaluates these rules sequentially when a ticket is categorized.
            </p>
            <div className="bg-[#150c19] rounded-xl p-6 border border-white/5">
               <pre className="text-xs text-slate-300 font-mono leading-relaxed overflow-x-auto">
{`rules:
  - name: "Route Access Issues"
    condition: "tags.intent == 'access_request'"
    actions:
      - set_queue: "IT-Support::Access"
      - add_note: "AI routed this to Access Team"

  - name: "Escalate Critical"
    condition: "tags.urgency == 'critical'"
    actions:
      - set_priority: "5 extreme"
      - notify_slack: "#incidents-critical"`}
               </pre>
            </div>
          </section>

          <section id="api" className="mb-32 pt-16 border-t border-white/5">
            <h2 className="text-3xl font-bold text-white mb-6 font-display">API Reference</h2>
            <p className="text-slate-400 mb-6 leading-relaxed">
              Trigger OTA manually or from other systems using the REST API.
            </p>
            <div className="bg-surface-dark rounded-xl border border-white/5 overflow-hidden">
              <div className="bg-[#1a101f] px-6 py-3 border-b border-white/5 flex items-center justify-between">
                <span className="text-[10px] font-black uppercase text-green-400">POST</span>
                <span className="text-xs text-slate-400 font-mono">/v1/automation/process</span>
              </div>
              <div className="p-6">
                <p className="text-xs text-slate-500 mb-4 font-mono">Payload Example:</p>
                <pre className="text-[11px] text-slate-300 bg-black/40 p-4 rounded-lg">
{`{
  "ticket_id": "100234",
  "tags": {
    "intent": "billing_dispute",
    "urgency": "medium"
  }
}`}
                </pre>
              </div>
            </div>
          </section>
        </div>
      </div>
    </div>
  );
};

export default OtaDocs;
