# Products Page Content (German)
hero:
  badge: '● LIVE CLASSIFICATION ENGINE v2.0'
  title:
    line1: 'Automatisierte,'
    line2: 'Konsistente Ticket-'
    line3: 'Klassifizierung'
    highlight: 'In Echtzeit.'
  description: 'Analysieren Sie eingehende Tickets und weisen Sie strukturierte, hierarchische Tags sofort zu. Keine Regeln zu pflegen. Vollständig automatisiert.'
  cta:
    primary: 'KONTAKTIEREN SIE DEN VERTRIEB'
    secondary: 'ROI-Rechner ansehen'

  demo:
    title: 'processor_v2.exe'
    input:
      label: 'ROHE EINGABE'
      subject: 'Login erneut fehlgeschlagen?'
      body: |
        Hallo Support, ich versuche auf
        das Dashboard zuzugreifen,
        aber erhalte Fehler 503. Das
        blockiert die Gehaltsabrechnung.
        Bitte beheben
    output:
      label: 'KI-STRUKTURIERTE AUSGABE'
      tags:
        - key: 'INTENT'
          value: 'access_issue'
          color: 'primary'
        - key: 'SYSTEM'
          value: 'dashboard_main'
          color: 'secondary'
        - key: 'URGENCY'
          value: 'critical'
          color: 'danger'

capabilities:
  title: 'Kernfunktionen'
  subtitle: 'Für Enterprise-Maßstab und Präzision entwickelt.'
  items:
    - icon: 'heroicons:cpu-chip'
      title: 'Vollautomatische Klassifizierung'
      description: 'Weist Tags für Intent, Dringlichkeit, Auswirkung, Benutzerrolle und Stimmung zu. Funktioniert nahtlos bei neuen Tickets und historischen Backlogs ohne menschliches Eingreifen.'
    - icon: 'heroicons:squares-2x2'
      title: 'Hierarchisch, nicht flach'
      description: 'Ein echter Taxonomiebaum. Übergeordnete Knoten für hochaggregierte Ansichten, Blatt-Tags für operative Präzision. Ermöglicht tiefgehende, mehrstufige Analysen.'
    - icon: 'heroicons:cube-transparent'
      title: '10 Billiarden Kombinationen'
      description: 'Ordnen Sie unsere feste, hochwertige Taxonomie Ihren benutzerdefinierten Feldern zu. Über 10 Billiarden mögliche Kombinationen, die zu jedem spezifischen Workflow oder jeder Branche passen.'

editions:
  title: 'Flexible Editionen'
  subtitle: 'Wählen Sie die Modellkomplexität, die Ihren operativen Anforderungen entspricht.'
  items:
    - slug: 'tagging-lite-free'
      name: 'Lite Free'
      subtitle: 'Evaluation & Testing'
      price: 0
      priceUnit: '/einmalig'
      currency: '€'
      badge: null
      features:
        - 'Model: 0.5B Parameter'
        - '150+ Tags'
        - 'Genauigkeit: ~0.82'
        - 'ROI: ab 15 Tickets/Tag'
      availability: 'Verfügbar 18.01'
      ctaText: 'Lite Free erkunden'
      highlighted: false

    - slug: 'tagging-lite-pro'
      name: 'Lite Pro'
      subtitle: 'Production Ready'
      price: 2500
      priceUnit: '/einmalig'
      currency: '€'
      badge: 'BEST VALUE'
      features:
        - 'Model: 4B Parameter'
        - '150+ Tags'
        - 'Genauigkeit: ~0.90'
        - 'Fokus: Routing & Reporting'
      availability: 'Verfügbar 18.01'
      ctaText: 'Lite Pro erkunden'
      highlighted: true

    - slug: 'tagging-full-pro'
      name: 'Full Pro'
      subtitle: 'Advanced Enterprise'
      price: 6000
      priceUnit: '/einmalig'
      currency: '€'
      badge: null
      features:
        - 'Model: 8B Parameter'
        - '250+ Tags'
        - 'Genauigkeit: ~0.92'
        - 'Fokus: Maximale Detailtiefe'
      availability: 'IN ENTWICKLUNG'
      ctaText: 'Full Pro erkunden'
      highlighted: false

  roiCta:
    icon: 'heroicons:rocket-launch'
    text: 'ROI-SIMULATOR AUSPROBIEREN'
    url: '/products/roi-calculator'

deployment:
  title: 'Bereitstellung & Hardware-Flexibilität'
  subtitle: 'Sicherheit durch Design. Optimiert für Ihre Infrastruktur.'
  features:
    - icon: 'heroicons:server'
      title: 'ON-PREMISE ODER PRIVATE CLOUD'
    - icon: 'heroicons:shield-check'
      title: 'KEINE DATEN VERLASSEN DIE INFRASTRUKTUR'
    - icon: 'heroicons:cube-transparent'
      title: 'INT8, BF16, FP16 QUANTIZATIONS'
    - icon: 'heroicons:cpu-chip'
      title: 'OPTIMIERT FÜR CPU & GPU'

finalCta:
  icon: 'heroicons:rocket-launch'
  title:
    line1: 'Verwandeln Sie rohe Tickets in'
    highlight: 'Operative Intelligenz.'
  subtitle: 'Schließen Sie sich zukunftsorientierten Support-Teams an, die ihren Workflow heute automatisieren.'
  buttons:
    primary: 'KONTAKTIEREN SIE DEN VERTRIEB'
    secondary: 'Dokumentation ansehen'
